<!-- top -->
<?php $college = $this->colleges[0]; ?>
	<div class="bigtab">
		<span class="position"><?php echo $college->place.' '.$this->translate('place').':';?></span>
		<a href="<?php echo $this->url(array('id'=>$college->id), 'college'); ?>" title="<?php echo sprintf($this->translate('go_to'), $college->name); ?>"><?php echo $college->name; ?></a>
		<span class="votes">
		<?php echo sprintf($this->translate(array('vote','votes', $college->votes)), $college->votes)?>
		</span>
		<a onclick="getItem ('<?php echo $college->id; ?>', 'colleges')" title="<?php echo sprintf($this->translate('vote_for'), $college->name); ?>" id="vote_button"><?php echo $this->translate('govote'); ?></a>
		<div style="clear: both;"></div>
	</div>
	<div class="leftcolumn">
	<h3><?php echo $this->translate('top 9 colleges') ?><a href="<?php echo $this->url(array('action'=>'all'))?>" title="<?php echo $this->translate('show_all')?>"><?php echo $this->translate('all_colleges') ?> &rsaquo;</a></h3>
Как взять <a href="http://kredit-belarus.by/kredit-na-obuchenie.html" title="Узнать о кредитах в Беларуси">кредит на учебу в Беларуси</a>
	<?php $i = 0; foreach($this->colleges as $college) : $i++;?>
	<?php if ($i != 1) :?>
		<div class="tab">
			<span class="numb"><?php echo $college->place;?></span>
			<a href="<?php echo $this->url(array('id'=>$college->id), 'college'); ?>" title="<?php echo sprintf($this->translate('go_to'), $college->name); ?>"><?php echo $college->name; ?></a>
			<span class="votes" title="<?php echo sprintf($this->translate(array('vote','votes', $college->votes)), $college->votes)?>"><?php echo $college->votes; ?></span>
			<a onclick="getItem ('<?php echo $college->id; ?>', 'colleges')" title="<?php echo sprintf($this->translate('vote_for'), $college->name); ?>" id="vote_button"><?php echo $this->translate('govote'); ?></a>
			<span class="descr"><?php echo $college->full_name; ?></span>
		</div>
	<?php endif;?>
<?php endforeach; ?>
    </div>
    <div class="rightcolumn">
        <h3><?php echo $this->translate('last records') ?></h3>
        <div id="notations">
    	</div>
        <script type="text/javascript">
            var thisUpdate = function(){
            	updateNotations('college', '', true, true);
            }
            window.onload = function(){
                thisUpdate();
            };
        </script>
    </div>