<?php echo $this->doctype() ?>

<html>
<head>
    <?php echo $this->headTitle() ?>
    
    <?php echo $this->headMeta() ?>
    
    <?php echo $this->headLink() ?>
    
    <?php echo $this->headStyle() ?>
    
    <?php echo $this->headScript() ?>
    
</head>
<body>
    <header>
        <div class="topmenu">
            <div class="content">
                <div class="logo">
                    <a href="/" title="go_home"><img src="/public/images/logo.png" alt="logo"></a>
                </div>
            </div>
        </div>
    </header>
	<div class="page">
	    <div class="content">
        <?php echo $this->layout()->content ?>
        
        </div>
    </div>
</body>
</html>