<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headTitle() ?>

        <?php echo $this->headMeta() ?>

        <?php echo $this->meta_facebook ?>

        <!-- Bootstrap -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <link rel="shortcut icon" href="/favicon.ico">

        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
		<meta name="msvalidate.01" content="B501B3654907BA421BA94C1CB83D607B" />
		<meta name="google-site-verification" content="wQ6nCfbyqdAw42kBLNqZyLtJf-kfALxnhocdckEKkB0" />
    </head>
    <body>
        <div class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">ТОП<span class="z">9</span></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php echo $this->navigation()->menu()->setMaxDepth(0)->renderPartial(null, 'menu.phtml'); ?>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown<?php echo $this->is_catalog ? ' active' : ''?>">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Каталоги <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/sites">Каталог сайтов</a></li>
                                <li><a href="/articles">Каталог статей</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="/articles/add" class=""><span class="glyphicon glyphicon-pencil"></span> Добавить статью</a>
                        </li>
                        <li>
                            <a href="/sites/add" class=""><span class="glyphicon glyphicon-plus-sign"></span> Добавить сайт</a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <div>
                <?php echo $this->layout()->content ?>
            </div>
            <hr>
            <footer>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="/sitemap.html"><span class="glyphicon glyphicon-globe"></span> Карта сайта</a> | <a href="#" data-toggle="modal" data-target="#contacts"><span class="glyphicon glyphicon-envelope"></span> Контакты</a>
                        <div class="modal fade bs-modal-sm" id="contacts" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h4 class="modal-title" id="myModalLabel">Как связаться</h4>
                                    </div>
                                    <div class="modal-body" id="social">
                                        <p><span class="glyphicon glyphicon-envelope"></span> evgen.kovalevich@gmail.com</p>
                                        <p><span class="glyphicon glyphicon-earphone"></span> 375(29)224-78-87</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="text-right"><span class="glyphicon glyphicon-copyright-mark"></span> Evgen.Kovalevich</div>
                        <br/>
                    </div>
                </div>
            </footer>
        </div> <!-- /container -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://code.jquery.com/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/js/bootstrap.min.js"></script>
        <script type="text/javascript">
            $('.progress div').hover(function(){
                $(this).popover('toggle');
            });
            $('img').error(function() {
                $(this).attr({
                    src: '/img/no-image.jpg', /* Путь до изображения, которое будет заменять отсутствующее */
                });
            });
        </script>
		
		<!-- Yandex.Metrika counter -->
		<script type="text/javascript">
		(function (d, w, c) {
			(w[c] = w[c] || []).push(function() {
				try {
					w.yaCounter21849814 = new Ya.Metrika({id:21849814,
							clickmap:true,
							trackLinks:true,
							accurateTrackBounce:true});
				} catch(e) { }
			});

			var n = d.getElementsByTagName("script")[0],
				s = d.createElement("script"),
				f = function () { n.parentNode.insertBefore(s, n); };
			s.type = "text/javascript";
			s.async = true;
			s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

			if (w.opera == "[object Opera]") {
				d.addEventListener("DOMContentLoaded", f, false);
			} else { f(); }
		})(document, window, "yandex_metrika_callbacks");
		</script>
		<noscript><div><img src="//mc.yandex.ru/watch/21849814" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
		<!-- /Yandex.Metrika counter -->
    </body>
</html>