<?php
$this->headTitle('Добавление статьи в каталог', 'PREPEND');
$this->headMeta('Публикация статей в каталоге. Продвижение статьями. SEO', 'description');
$this->headMeta('каталог статей, публикации, seo, продвижение статьями', 'keywords');
?>

<ol class="breadcrumb">
    <li><a href="/">Главная</a></li>
    <li><a href="/articles">Каталог статей</a></li>
    <li class="active">Добавить статью</li>
</ol>

<div class="page-header">
    <h1>Опубликовать статью <small>быстро и просто</small></h1>
</div>

<?php if($this->message): ?>
    <div class="alert alert-success"><?php echo $this->message; ?></div>
    <a href="/articles" class="btn btn-default">К статьям</a> <a href="/articles/add" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span> Добавить еще статью</a>
<?php else: ?>

    <?php if($this->errors): ?>
        <div class="alert alert-danger"><?php echo $this->errors; ?></div>
    <?php endif; ?>

    <div class="row">
        <form class="form-horizontal col-sm-9" role="form" method="post">

            <div class="form-group">
                <label for="category" class="col-sm-3 control-label">Категория</label>
                <div class="col-sm-9">
                    <select name="category_id" id="category" class="form-control">
                        <?php foreach ($this->categories as $category): ?>
                            <option value="<?php echo $category->id; ?>"><?php echo $category->title; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="title" class="col-sm-3 control-label">Заголовок статьи</label>
                <div class="col-sm-9">
                    <input type="text" name="title" class="form-control" id="title" value="<?php echo $this->form->title->getValue() ?>" placeholder="Заголовок">
                </div>
            </div>

            <div class="form-group">
                <label for="text" class="col-sm-3 control-label">Текст</label>
                <div class="col-sm-9">
                    <textarea id="editor" name="text" rows="10" cols="80">
                        <?php echo $this->form->text->getValue() ?>
                    </textarea>
                    <script src="/js/ckeditor/ckeditor.js"></script>
                    <script>
                        CKEDITOR.replace( 'editor', {
							'extraPlugins': 'imagebrowser',
							'filebrowserBrowseUrl' : '/js/pdw_file_browser/index.php?editor=ckeditor',
							'filebrowserImageBrowseUrl' : '/js/pdw_file_browser/index.php?editor=ckeditor&filter=image',
                            toolbar:
                                [
                                    { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
                                    { name: 'insert', items : [ 'Image','Table','HorizontalRule','SpecialChar'] },
                                    '/',
                                    { name: 'basicstyles', items : ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
                                    { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
                                    '/',
                                    { name: 'paragraph', items : [ 'NumberedList','BulletedList' ] },
                                    { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                                    { name: 'tools', items : [ 'Maximize', 'ShowBlocks' ] }
                                ]
                        });
                    </script>
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">Ваш email для связи</label>
                <div class="col-sm-9">
                    <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-success">Опубликовать</button>
                </div>
            </div>
        </form>
        <div class="col-sm-3">
            <div class="alert alert-warning">
                <h3>Правила публикации</h3>
                <ul>
                    <li>В каталог принимаются только уникальные статьи</li>
                    <li>Статья должна быть содержательной</li>
                    <li>Материал может содержать не более 3 внешних ссылок</li>
                    <li>Все ссылки с одной статьи могут вести только на один ресурс</li>
                    <li>Статья должна быть написанна грамотно и без грамматических ошибок</li>
                    <li>Запрещена публикация материалов, нарушающих действующее законодательство РБ</li>
                </ul>
                <hr class="half-rule">
                <p><span class="glyphicon glyphicon-exclamation-sign"></span> Статьи с нарушением правил будут бесповоротно удалены!</p>
            </div>
        </div>
    </div>

<?php endif;?>
