<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    <?php foreach ($this->pages as $page) :?>
        <url>
            <loc><?php echo $page['loc'] ?></loc>
            <lastmod><?php echo $page['lastmod'] ?></lastmod>
            <changefreq>weekly</changefreq>
            <priority><?php echo $page['priority'] ?></priority>
        </url>
    <?php endforeach; ?>

</urlset>