<?php
$this->headTitle('Добавление сайта в каталог', 'PREPEND');
$this->headMeta('Добавить сайт в каталог top9.by. Продвижение статьями. SEO', 'description');
$this->headMeta('каталог сайтов, сайты, seo, продвижение статьями', 'keywords');
?>

<ol class="breadcrumb">
    <li><a href="/">Главная</a></li>
    <li><a href="/sites">Каталог сайтов</a></li>
    <li class="active">Добавить сайт</li>
</ol>

<div class="page-header">
    <h1>Добавить сайт <small>за 60 секунд</small></h1>
</div>

<?php if($this->message): ?>
    <div class="alert alert-success"><?php echo $this->message; ?></div>
    <a href="/sites" class="btn btn-default">В каталог сайтов</a> <a href="/sites/add" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> Добавить другой сайт</a>
<?php else: ?>

    <?php if($this->errors): ?>
        <div class="alert alert-danger"><?php echo $this->errors; ?></div>
    <?php endif; ?>

    <div class="row">
        <form class="form-horizontal col-sm-9" role="form" method="post">

            <div class="form-group">
                <label for="category" class="col-sm-3 control-label">Категория</label>
                <div class="col-sm-9">
                    <select name="category_id" id="category" class="form-control">
                        <?php foreach ($this->categories as $category): ?>
                            <option value="<?php echo $category->id; ?>"><?php echo $category->title; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="title" class="col-sm-3 control-label">Название сайта</label>
                <div class="col-sm-9">
                    <input type="text" name="title" class="form-control" id="title" value="<?php echo $this->form->title->getValue() ?>" placeholder="Мой сайт">
                </div>
            </div>

            <div class="form-group">
                <label for="id" class="col-sm-3 control-label">Адрес сайта</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <span class="input-group-addon">http://</span>
                        <input type="text" name="id" class="form-control" id="id" value="<?php echo $this->form->id->getValue() ?>" placeholder="site.by">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="description" class="col-sm-3 control-label">Описание</label>
                <div class="col-sm-9">
                    <textarea id="editor" name="description" rows="10" cols="80">
                        <?php echo $this->form->description->getValue() ?>
                    </textarea>
                    <script src="/js/ckeditor/ckeditor.js"></script>
                    <script>
                        CKEDITOR.replace( 'editor', {
							'extraPlugins': 'imagebrowser',
							'filebrowserBrowseUrl' : '/js/pdw_file_browser/index.php?editor=ckeditor',
							'filebrowserImageBrowseUrl' : '/js/pdw_file_browser/index.php?editor=ckeditor&filter=image',
                            toolbar:
                                [
                                    { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
                                    { name: 'insert', items : [ 'Image','Table','HorizontalRule','SpecialChar'] },
                                    '/',
                                    { name: 'basicstyles', items : ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
                                    { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
                                    '/',
                                    { name: 'paragraph', items : [ 'NumberedList','BulletedList' ] },
                                    { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                                    { name: 'tools', items : [ 'Maximize', 'ShowBlocks' ] }
                                ]
                        });
                    </script>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button type="submit" class="btn btn-success">Отправить</button>
                </div>
            </div>
        </form>
        <div class="col-sm-3">
            <div class="alert alert-warning">
                <h3>Правила добавления</h3>
                <ul>
                    <li>В каталог принимаются только рабочие и качественные сайты</li>
                    <li>Сайт должен быть информативным, или предоставляющим услуги</li>
                    <li>Сайт должен иметь отношение к Беларуси</li>
                    <li>Содержимое сайта, включая рекламные баннеры, не должно нарушать действующего законодательства РБ</li>
                </ul>
                <hr class="half-rule">
                <p><span class="glyphicon glyphicon-exclamation-sign"></span> Сайты с нарушением правил будут бесповоротно удалены!</p>
            </div>
            <div class="alert alert-info">
                <p>Ваш сайт может быть удален из каталога на наше усмотрение без объяснения причин. Наш каталог предназначен только для качественных и полезных сайтов и призван приносить пользу вебмастерам и аудитории. Отнеситесь к этому с пониманием!</p>
            </div>
        </div>
    </div>

<?php endif;?>
