<?php
$this->headTitle('Каталог сайтов / ' . $this->category->title, 'PREPEND');
$this->headMeta($this->category->description, 'description');
$this->headMeta('каталог сайтов, сайты, seo, продвижение статьями', 'keywords');
?>

<ol class="breadcrumb">
    <li><a href="/">Главная</a></li>
    <li><a href="/sites">Каталог сайтов</a></li>
    <li class="active"><?php echo $this->category->title; ?></li>
</ol>

<div class="row">
    <div class="col-sm-9 blog-main">
        <?php foreach($this->sites as $site): ?>
            <div class="blog-post">
                <h3 class="blog-post-title"><a href="<?php echo $this->url(array('id'=>$site->id, 'category'=>$site->category->id), 'site')?>" title="На страницу сайта"><?php echo $site->title ?></a></h3>
                <p class="blog-post-meta"><a href="http://<?php echo $site->id ?>" target="_blank"><span class="glyphicon glyphicon-link"></span> <?php echo $site->id ?></a> | в каталоге с <?php echo $this->nicetime($site->created) ?></p>

                <?php echo $this->truncate($site->description, 400) ?>
            </div><!-- /.blog-post -->
        <?php endforeach; ?>
        <?php echo $this->paginator ?>
    </div>
    <div class="col-sm-3">

    </div>
</div>